apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-rds
spec:
  package: xpkg.upbound.io/upbound/configuration-rds:v0.0.3
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false